# -*- coding: utf-8 -*-
"""5210411236_Tabia Hanural

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZXJQLIFZcKdHbQ-n3Nqi3a3E0v8eX0uB

# ***Menghitung Luas Lingkaran***
"""

# rumus : π*r^2

nilai_phi = float(input("Masukkan nilai phi : "))
nilai_r = int(input("Masukkan nilai jari-jari : "))

nilai_total = nilai_phi * nilai_r * nilai_r

print("")
print("Hasil nilai luas lingkaran : ", nilai_total)

"""# ***Tabia Hanural (5210411236)***"""