# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NK1s624yBSEKRKkp4sM_tlRtU5XhRCEq

# ***NIM : 5210411236***
# ***Nama : Tabia Hanural***

# ***STRING***
"""

'Ini namanya string'
"Ini juga namanya string"

x="Universitas Teknologi Yogyakarta"
print(x)

y=x
print(y)

z=" adalah universitas saya"
hasil = x + z
print(hasil)

m = "Nama saya adalah Tabia Hanural"
print(m[17])
print(m[:16])
print(m[17:])

x = "AKU ANAK HEBAT"
print(x)
xy = x[:9] + "BLORA MUSTIKA" + x[8:]
print(xy)

x = "Universitas Teknologi Yogyakarta"
up = x.upper()
low = x.lower()
print(x)
print(up)
print(low)
print()

len(x)
jumlah=len(x)
print("Jumlah panjang string adalah " ,jumlah)

a = "satu"
b = "dua"
c = "tiga"
print("Saya mempunyai %s mangga." % (c))
print()

data1 = input("String 1: ")
data2 = input("String 2: ")
hasil = data1 + data2
print(hasil)

"""# ***LIST***"""

list1 = ['fisika', 'kimia', 1993, 2017]
list2 = [1, 2, 3, 4, 5, 6, 7 ]

print ("list1: ", list1)
print ("list1[0]: ", list1[0])
print ("list2[1:5]: ", list2[1:5])

list = ['fisika', 'kimia', 1993, 2017]
print ("Nilai ada pada index 2 : ", list[2])

list[2] = 2001
print ("Nilai baru ada pada index 2 : ", list[2])

list = ['fisika', 'kimia', 1993, 2017]
print(list)
del list[2]
print ("Setelah dihapus nilai pada index 2 : ", list)

"""# ***DICTIONARY***"""

dict = {'Name': 'Zara', 'Age': 7, 'Class': 'First'}
print (dict)
print (dict['Name'])
print (dict['Age'])

dict = {'Name': 'Zara', 'Age': 7, 'Class': 'First'}
dict['Age'] = 8
dict['School'] = "DPS School"

print (dict['Age'])
print (dict['School'])

dict = {'Name': 'Zara', 'Age': 7, 'Class': 'First'}

del dict['Name'] 
dict.clear()

"""# ***TUPLE***"""

tup1 = ('fisika', 'kimia', 1993, 2017)
tup2 = (1, 2, 3, 4, 5, 6, 7 )

print (tup1)
print (tup1[0])
print (tup2[1:5])

tup1 = (12, 34, 56)
tup2 = ('abc', 'xyz')
tup3 = tup1 + tup2
print (tup3)

tup = ('fisika', 'kimia', 1993, 2017)
print(tup)

del tup

tup = ('Bahasa', 'Literasi', 2020)
print("Setelah menghapus tuple :", tup)

"""# ***SET***"""

a = [1,2,3,4,5]
s = set(a)
s

himpunan_abjad = {'a', 'b', 'c'}
print(himpunan_abjad)

himpunan_abjad.add('d')
himpunan_abjad.add('e')
himpunan_abjad.update({ 'f', 'g' })
himpunan_abjad.update(['h', 'i'])
print(himpunan_abjad)

himpunan = {'maya', 'budi', 100, ('a', 'b'), False, True}
print(himpunan)

himpunan.remove(100)
print(himpunan)

himpunan.discard(('a', 'b'))
print(himpunan)

nilaiYangDihapus = himpunan.pop()
print('nilaiYangDihapus =', nilaiYangDihapus)
print(himpunan)

himpunan.clear()
print(himpunan)