# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fZmMjTD3GQW99MaQkRcL1W8ndIw2yq2m
"""

class Titik:
  def __init__(self,x,y):
    self.x = x
    self.y = y

titik_a = Titik(0,3)
titik_b = Titik(5,4)
print('Titik A memiliki koordinat ({},{})'.format(titik_a.x,titik_a.y))
print('Titik B memiliki koordinat ({},{})'.format(titik_b.x,titik_b.y))

class MenuMinuman:
  def __init__(self,nama,deskripsi,harga):
    self.nama = nama
    self.deskripsi = deskripsi
    self.harga = harga

mnm1 = MenuMinuman('Jus Jambu','Jus Jambu Merah Tanpa Gula',8500)
mnm2 = MenuMinuman('Jus Alpukat','Jus Alpukat Dengan Tambahan Air Gula Merah',15000)
mnm3 = MenuMinuman('Jus Alpukat Extra Milk','Jus Alpukat Dengan Campuran Susu Coklat dan Taburan Kepingan Choco',15000)
mnm4 = MenuMinuman('Red & Smooth','Smoothie Pisang Susu Dengan Strawberry',17500)

pilihan_minuman = [mnm1,mnm2,mnm3,mnm4]
print('Daftar menu Healthy Fruits')
for m in pilihan_minuman:
  t = '{} harga Rp {}, {}'.format(m.nama,m.harga,m.deskripsi)
  print(t)

class BukuSejarah:
  def __init__(self,judul,pengarang,tahun):
    self.judul = judul
    self.pengarang = pengarang
    self.tahun = tahun

buku = BukuSejarah('Tenggelamnya Kapal Van der Wijck','HAMKA',1938)
t = 'Buku Sejarah {} karangan {} pertama kali diterbitkan tahun {}'.format(buku.judul,buku.pengarang,buku.tahun)
print(t)

class Titik:
  def __init__(self,x,y):
    self.x = x
    self.y = y

class Garis:
  def __init__(self,titik1,titik2):
    self.titik1 = titik1
    self.titik2 = titik2

  def panjang(self):
    pjg_x = self.titik2.x - self.titik1.x
    pjg_y = self.titik2.y - self.titik1.y
    pjg = (pjg_x**2 + pjg_y**2) ** 0.5
    return pjg

titik_a = Titik(0,0)
titik_b = Titik(3,4)
garis_ab = Garis(titik_a,titik_b)
print('Panjang garis ab adalah {}'.format(garis_ab.panjang()))

class Mahasiswa:
  def __init__(self,nama,nim,prodi,tahun):
    self.nama = nama
    self.nim = nim
    self.prodi = prodi
    self.tahun = tahun
m1 = Mahasiswa('Udin','10120371','Sistem Informasi',2020)
teks = '{} adalah mahasiswa {} angkatan {} dengan NIM {}'.format(m1.nama,m1.prodi,m1.tahun,m1.nim)
print(teks)

class MenuMakanan:
  def __init__(self,nama,deskripsi,harga):
    self.nama = nama
    self.deskripsi = deskripsi
    self.harga = harga

mkn1 = MenuMakanan('Nasi Padang','Nasi Padang Dengan Daging Sapi',15000)
mkn2 = MenuMakanan('Bakso','Bakso Dengan Tambahan Lontong',12000)
mkn3 = MenuMakanan('Nasi Goreng','Nasi Goreng Dengan Campuran Sosis dan Telur Dadar',15000)
mkn4 = MenuMakanan('Mie Ayam','Mie Ayam Dengan Tambahan Pangsit',12000)

pilihan_makanan = [mkn1,mkn2,mkn3,mkn4]
print('Daftar menu Healthy Fruits')
for m in pilihan_makanan:
  t = '{} harga Rp {}, {}'.format(m.nama,m.harga,m.deskripsi)
  print(t)

class Mahasiswi:
  def __init__(self,nama,nim,prodi,tahun):
    self.nama = nama
    self.nim = nim
    self.prodi = prodi
    self.tahun = tahun
m1 = Mahasiswi('Salma','10120371','Informatika',2021)
teks = '{} adalah mahasiswi {} angkatan {} dengan NIM {}'.format(m1.nama,m1.prodi,m1.tahun,m1.nim)
print(teks)

class BukuCerpen:
  def __init__(self,judul,pengarang,tahun):
    self.judul = judul
    self.pengarang = pengarang
    self.tahun = tahun

buku = BukuCerpen('Filosofi Kopi','DEE LESTARI',2006)
t = 'Buku Cerpen {} karangan {} pertama kali diterbitkan tahun {}'.format(buku.judul,buku.pengarang,buku.tahun)
print(t)