# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Rj52OtsedVUT0iCiA_q_UlHJd7JuOyq
"""

# PUBLIC
class Segitiga:
  def __init__(self,alas,tinggi):
    self.alas= alas
    self.tinggi = tinggi
    self.luas = 0.5 * alas * tinggi
  
segitiga_besar = Segitiga(100,80)

print("Alas: ",segitiga_besar.alas)
print("Tinggi: ",segitiga_besar.tinggi)
print("Luas: ",segitiga_besar.luas)

# PROTECTED
class Utama:
  def __init__(self):
    self._a = 2

class Turunan(Utama):
  def __init__(self):
    Utama.__init__(self)
    print("Memanggil variabel protected pada class Utama: ",self._a)

    self._a = 3
    print("Memanggil variabel protected yang dimodifikasi diluar class: ",self._a)

objek1 = Turunan()
objek2 = Utama()

print("Mengakses variabel protected dari objek1: ",objek1._a)
print("Mengakses variabel protected dari objek2: ",objek2._a)

# PRIVATE
class Hitung:
  def __init__(self):
    self. __angkaRahasia = 0
  def tampilkanHitung(self):
    self. __angkaRahasia += 1
    print(self. __angkaRahasia)

hitungan = Hitung()
hitungan.tampilkanHitung()

hitungan.tampilkanHitung()

hitungan._Hitung__angkaRahasia

# PUBLIC
class Mobil():
  def __init__(self,jendela,pintu,mesin):
    self.jendela=jendela
    self.pintu=pintu
    self.mesin=mesin

# PROTECTED
class Mobil():
  def __init__(self,jendela,pintu,mesin):
    self._jendela=jendela
    self._pintu=pintu
    self._mesin=mesin

class Truk():
  def __init__(self,jendela,pintu,mesin,tipe):
    super().__init__(jendela,pintu,mesin)
    self.tipebak=tipe

# PRIVATE
class Mobil():
  def __init__(self,jendela,pintu,mesin):
    self.__jendela=jendela
    self.__pintu=pintu
    self.__mesin=mesin

# FUNGSI PRIVATE & PUBLIC
class Pegawai:
  __nama=""
  __alamat=""
  __gaji=0

  def __init__(self,nama,alamat):
    self.__nama=nama
    self.__alamat=alamat

  def __hitungGaji(self):
    upahLembur=20000
    gajiPokok=2000000
    jumlahLembur=int(input("Total jam lembur: "))
    self.__gaji=(upahLembur*jumlahLembur)+gajiPokok

  def tampilDetail(self):
    print("\n-- Menghitung dan Menampilkan Detail Gaji Pegawai --")
    print("Nama: ",self.__nama)
    print("Alamat: ",self.__alamat)
    self.__hitungGaji()
    print("Total Gaji: ",self.__gaji)

pgw1=Pegawai("Mikasa Ackerman","Wall Rose")
pgw1.tampilDetail()

pgw2=Pegawai("Rini Kesud","Burhan Street")
pgw2.tampilDetail()

class Menu:
  def __init__(self,nama,deskripsi,harga):
    self.__nama = nama
    self.__deskripsi = deskripsi
    self.__harga = harga

  def tampilDetail(self):
    print("\n-- Menampilkan Detail Menu --")
    print()
    print("Nama      : ",self.__nama)
    print("Harga     : ",self.__harga)
    print("Deskripsi : ",self.__deskripsi)

mn1 = Menu("Nasi Padang",15000,"Nasi Padang Dengan Daging Sapi")
mn1.tampilDetail()

class Mahasiswa:
  def __init__(self,nama,nim,prodi,tahun):
    self.__nama = nama
    self.__nim = nim
    self.__prodi = prodi
    self.__tahun = tahun

  def tampilDetail(self):
    print("\n-- Menampilkan Detail Data Mahasiswa --")
    print()
    print("Nama  : ",self.__nama)
    print("NIM   : ",self.__nim)
    print("Prodi : ",self.__prodi)
    print("Tahun : ",self.__tahun)

mh1 = Mahasiswa("Tabia Hanural",5210411236,"Informatika",2021)
mh1.tampilDetail()

class Buku:
  def __init__(self,judul,pengarang,tahun,stok):
    self.__judul = judul
    self.__pengarang = pengarang
    self.__tahun = tahun
    self.__stok = stok

  def tampilDetail(self):
    print("\n-- Menampilkan Detail Data Buku --")
    print()
    print("Judul     : ",self.__judul)
    print("Pengarang : ",self.__pengarang)
    print("Tahun     : ",self.__tahun)
    print("Stok      : ",self.__stok)

bk1 = Buku("Tenggelamnya Kapal Van der Wijck","Hamka",1938,17)
bk1.tampilDetail()