# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16f7pGxfFnt2sKO1QK0oQDYQrylQPVLxp
"""

# MODIFIKASI CLASS DIAGRAM

class PerpusItem:
  def __init__(self, judul, subjek, lokasi, info):
    self.judul = judul
    self.subjek = subjek
    self.lokasi = lokasi
    self.info = info

  '''def lokasiSimpan(self):
   self.lokasi = lokasi
   self.info = info
'''

class Buku(PerpusItem):
  def __init__(self,judul,subjek,lokasi,info,isbn,pengarang,jmlhal,ukuran):
    super().__init__(judul,'Buku',lokasi,info)
    self.isbn = isbn
    self.pengarang = pengarang
    self.jmlhal = jmlhal
    self.ukuran = ukuran

class Majalah(PerpusItem):
  def __init__(self,judul,subjek,lokasi,info,volume,issue):
    super().__init__(judul,'Majalah',lokasi,info)
    self.volume = volume
    self.issue = issue

class DVD(PerpusItem):
  def __init__(self,judul,subjek,lokasi,info,aktor,genre):
    super().__init__(judul,'DVD',lokasi,info)
    self.aktor = aktor
    self.genre = genre

class Komik(PerpusItem):
  def __init__(self,judul,subjek,lokasi,info,tema,terbit):
    super().__init__(judul,'Komik',lokasi,info)
    self.tema = tema
    self.terbit = terbit

b = Buku('Pemrograman Python','Buku Cetak','Rak nomor 1','Dipinjam','945-884-98-02','Yogi Syarif',2,'25x15')
m = Majalah('Dunia Komputer','Majalah Cetak','Rak nomer 2','ada','VII','Komputer')
d = DVD('Shingeki no kyojin','sofcopy','Rak nomor 3','ada','Mikasa','Anime')
n = Komik('Saitama','Komik Jepang','Rak nomer 4','Dipinjam','Superhero','2012')

daftar = [b,m,d,n]
for dft in daftar:
  print('{} {} {} {}'.format(dft.judul,dft.subjek,dft.lokasi,dft.info))

class PerpusItem:
  def __init__(self, judul, subjek, lokasi, info):
    self.judul = judul
    self.subjek = subjek
    self.lokasi = lokasi
    self.info = info

  '''def lokasiSimpan(self):
   self.lokasi = lokasi
   self.info = info
'''

class Buku(PerpusItem):
  def __init__(self,judul,subjek,lokasi,info,isbn,pengarang,jmlhal,ukuran):
    super().__init__(judul,'Buku',lokasi,info)
    self.isbn = isbn
    self.pengarang = pengarang
    self.jmlhal = jmlhal
    self.ukuran = ukuran

class Majalah(PerpusItem):
  def __init__(self,judul,subjek,lokasi,info,volume,issue):
    super().__init__(judul,'Majalah',lokasi,info)
    self.volume = volume
    self.issue = issue

class DVD(PerpusItem):
  def __init__(self,judul,subjek,lokasi,info,aktor,genre):
    super().__init__(judul,'DVD',lokasi,info)
    self.aktor = aktor
    self.genre = genre

b = Buku('Pemrograman Python','Buku Cetak','Rak nomor 1','Dipinjam','945-884-98-02','Yogi Syarif',2,'25x15')
m = Majalah('Dunia Komputer','Majalah Cetak','Rak nomer 2','ada','VII','Komputer')
d = DVD('Shingeki no kyojin','sofcopy','Rak nomor 3','ada','Mikasa','Anime')

daftar = [b,m,d,]
for dft in daftar:
  print('{} {} {} {}'.format(dft.judul,dft.subjek,dft.lokasi,dft.info))

# MODIFIKASI MENU CARI BUKU

import os
def perpusItem (msg):
  input(msg)
  if os.name == "posix":
    os.system("clear")
  else:
    os.system("cls")

def mainMenu(x):
  if x == "1":
    readal1()

  elif x == "2":
    judul = input("Masukan Judul Buku : ")
    create(judul)

  elif x == "3":
    judul = input("Input Judul Yang Dicari : ")
    readone(judul)

  elif x == "4":
    judul = input("Input Judul Yang Dicari : ")
    delete(judul)

  elif x == "5":
    print("Program Shutting Down..")

  else:
    print("Option Not Found.")

def create(judul):
  buku.append(judul)
  perpusItem("Data berhasil ditambahkan, Press any key to continue..")

def readal1():
  print("Daftar Buku : ")
  no = 1
  for i in buku:
    print(str(no)+","+i)
    no +=1
    perpusItem("Press any key to continue...")

def readone(judul):
  filter_object = filter(lambda a: judul in a, buku)
  p = list(filter_object)
  if(not p):
    perpusItem("Data tidak ditemukan, Press any key to continue...")
  else:
    perpusItem("Buku berjudul '"+",".join(p)+"' berhasil ditemukan.")

def delete(judul):
  if buku.count(judul) >= 1:
    buku.remove(judul)
    perpusItem("Data berhasil dihapus, Press any key to continue...")
  else: 
    perpusItem("Buku tidak ditemukan.Harap mengetik secara detail untuk keamanan.")

buku = ["suara orang kampung", "mimpi orang sinting", "Hikayat Pohon Ganja", "Dunia Yang Dsembunyikan"]

x = "0"
while x != "5":
  print("Program Perpustakaan UTY")
  print("[1] Tampilkan Semua Data Buku")
  print("[2] Tambahkan Data Buku")
  print("[3] Cari Buku")
  print("[4] Hapus Buku")
  print("[5] Exit")
  print()

  x = input("Pilihan : ")
  mainMenu(x)